spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migrations
    user: postgres
microservices:
  payment: http://localhost:8003
  order: http://localhost:8001
  inventory: http://localhost:8002
  shipping: http://localhost:8004
  gateway: http://localhost:8005
  bill: http://localhost:8006
  notification: http://localhost:8007
  product: http://localhost:8008
  cargo: http://localhost:8009
  shoppingcart: http://localhost:8010
