spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migrations
    user: postgres
microservices:
  services:
    gateway: http://192.168.137.149:8001       # Gateway Servisi
    product: http://192.168.137.35:8002       # Ürün Servisi
    order: http://192.168.137.169:8003         # Sipariş Servisi
    notification: http://192.168.137.111:8004   # Bildirim Servisi
    cart: http://192.168.137.244:8005          # Alışveriş Sepeti Servisi
    payment: http://192.168.137.52:8006       # Ödeme Servisi
    user: http://192.168.137.195:8007          # Kullanıcı Servisi
    invoice: http://192.168.137.140:8008       # Fatura Servisi
    shipment: http://192.168.137.179:8011
